### ISSUE TITLE
Could be the documentation outdated?

### ISSUE THREAD

**Issue by lpalomerol** [WGLab/GenGen#3]
Hello again, 

I am following the documenation in order to perform pathway analysis from GWAS output and I some discrepancies between it and real data. When you see 

> If you happen to use calculate_association.pl program to calculate the chi2 and P-values in 1000 permutation cycles, this file can indeed be easily generated from the association permutation results file (see below), by taking the second and sixth column of the association permutation results file.

I think should be first and seventh field, which are labeled with "Name" and "ALLELIC_chi2" names, could be?

Second one is the output of the head gsea.cc10 file, which seems also different than mine.

Thirdly, should be necessary perform permutation tests? Could be suitable work only with the results o case-control tests? I've got the output of both files (with and without permutations) and statistical values are identical.

Thanks again!

**Comment by kaichop** [comment]
It could be that different type of tests (quantitative trait regression,
allelic test, dominant/recessive model test, etc) have different header,
since allelic_chi2 is only for allelic test; from your description, it is
the Name and allelic_chi2 for your files. The header may differ since
different association models may have been used.
It is generally necessary to perform permutation tests on phenotypes (i.e.
case control status are randomly perturbed and p-values are re-calculated
for every SNP). The permututation test results file may contain one column
without permutation (original results), as well as many columns with
permutation (say 100 permutation cycles generate 100 chi2 values per line).

**Comment by lpalomerol** [comment]
Tank you very much! Works like a charm!
